services:
  embeddings-trainer:
    build: .
    container_name: word2vec_trainer
    volumes:
      - ./models:/models
      - ./datasets:/datasets
      - ./checkpoints:/checkpoints
    env_file:
      - .env  # These variables will be loaded into the container's environment.
    environment:
      # Override variables if needed; otherwise, they will use the values from .env.
      DATASET_URL: https://dumps.wikimedia.org/enwiki/latest/enwiki-latest-pages-articles.xml.bz2
      MODEL_NAME: word2vec_enwiki-latest-pages-articles
      MODEL_TYPE: Word2Vec
      MODEL_TRAIN: true
      CORPUS_CHECKPOINT_STRATEGY: streaming
      UPLOAD_TO_VECTORDB: true
      VECTORDB_HOST: qdrant
      VECTORDB_COLLECTION: word2vec_enwiki-latest-pages-articles
    depends_on:
      - qdrant

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  qdrant_data: