services:
  word2vec-trainer:
    build: .
    container_name: word2vec_trainer
    volumes:
      - ./datasets:/app/datasets
      - ./models:/app/models
    env_file:
      - .env  # This file will be read, and its variables set into the container's environment
    environment:
      # Optionally override any env settings here if needed; otherwise, rely on .env.
      # For example, you could override WIKI_PATH & WIKI_URL for a different language version.
      WIKI_PATH: datasets/rowiki-latest-pages-articles.xml.bz2
      WIKI_URL: https://dumps.wikimedia.org/rowiki/latest/rowiki-latest-pages-articles.xml.bz2
      MODEL_NAME: word2vec_ro
      EPOCHS: 1
      UPLOAD_TO_QDRANT: false
      QDRANT_HOST: qdrant
      QDRANT_COLLECTION: word2vec_ro
    depends_on:
      - qdrant

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  qdrant_data:
